package catalogyaml

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/Muratovnik/routevane/internal/domain"
	"github.com/Muratovnik/routevane/internal/planner"
	"github.com/Muratovnik/routevane/internal/renderers/keenetic"
	"github.com/Muratovnik/routevane/internal/renderers/singbox"
)

func draftDefinition() domain.ServiceDefinition {
	return domain.ServiceDefinition{
		ID:         "example",
		Title:      "example.co.uk",
		Components: []domain.ComponentDefinition{{ID: "core", Required: true}},
		Seeds: []domain.Seed{
			{Kind: domain.RuleDomainSuffix, Value: "example.co.uk", ComponentID: "core", SourceClass: domain.SourceManual},
		},
		DNSNames: []string{"example.co.uk", "www.example.co.uk"},
		Sources: []domain.SourceDefinition{{
			ID: "dns-core", Type: domain.SourceDNS, ComponentID: "core",
			Names: []string{"www.example.co.uk", "example.co.uk"},
		}},
	}
}

func TestWriteLocalDraftProducesADefinitionTheProductCanLoad(t *testing.T) {
	root := t.TempDir()
	path, err := WriteLocalDraft(context.Background(), root, draftDefinition())
	if err != nil {
		t.Fatal(err)
	}
	if filepath.Base(path) != "example.yaml" || filepath.Base(filepath.Dir(path)) != LocalGroup {
		t.Fatalf("path = %s", path)
	}
	payload, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	text := string(payload)
	if !strings.HasPrefix(text, "# Generated by Routevane discovery.") {
		t.Fatalf("draft is missing its review header:\n%s", text)
	}
	// A draft carries domains only. An address or a network here would be the
	// widening this boundary forbids.
	for _, forbidden := range []string{"/24", "/32", "192.0.2", "203.0.113", "ip_cidr", "prefix"} {
		if strings.Contains(text, forbidden) {
			t.Fatalf("draft contains %q:\n%s", forbidden, text)
		}
	}

	catalog, err := Load(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	service, found := catalog.Service("example")
	if !found || len(service.Sources) != 1 {
		t.Fatalf("loaded service = %#v", service)
	}
	if strings.Join(service.Sources[0].Names, ",") != "example.co.uk,www.example.co.uk" {
		t.Fatalf("source names are not canonical: %#v", service.Sources[0].Names)
	}
	if service.Sources[0].Revision == "" {
		t.Fatal("a loaded draft source needs an active revision")
	}
}

func TestADiscoveredDraftIsImmediatelyUsableByTheExistingRenderers(t *testing.T) {
	root := t.TempDir()
	if _, err := WriteLocalDraft(context.Background(), root, draftDefinition()); err != nil {
		t.Fatal(err)
	}
	catalog, err := Load(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	definition, found := catalog.Service("example")
	if !found {
		t.Fatal("draft did not load")
	}
	now := time.Date(2026, 8, 21, 12, 0, 0, 0, time.UTC)
	resource, err := domain.NewAddrResourceFromString("192.0.2.10")
	if err != nil {
		t.Fatal(err)
	}
	sighting := domain.Sighting{
		ServiceID: "example", ComponentID: "core", Resource: resource,
		SourceID: "dns-core", SourceClass: domain.SourceObserved, SourceRevision: definition.Sources[0].Revision,
		ValidUntil: now.Add(time.Hour), Validity: domain.ValidityValid,
	}

	routerTarget := domain.TargetProfile{
		ID: "keenetic", ProfileKey: keenetic.Version, RendererID: keenetic.ID,
		Constraints: domain.TargetConstraints{SupportsIPv4: true, SupportsPrefixes: true, MaxRules: keenetic.MaxLines, MaxArtifactSize: keenetic.MaxArtifactSize},
	}
	routerPlan, err := planner.BuildPlanSet([]planner.ServiceInput{{Definition: definition, Sightings: []domain.Sighting{sighting}}}, routerTarget, now)
	if err != nil {
		t.Fatal(err)
	}
	routerArtifact, err := keenetic.Render(routerPlan)
	if err != nil {
		t.Fatal(err)
	}
	if err := keenetic.Validate(routerArtifact); err != nil {
		t.Fatalf("router artifact from a discovered draft is invalid: %v", err)
	}
	if !strings.Contains(string(routerArtifact), "192.0.2.10") {
		t.Fatalf("router artifact = %s", routerArtifact)
	}

	clientTarget := domain.TargetProfile{
		ID: "singbox", ProfileKey: singbox.Version, RendererID: singbox.ID,
		Constraints: domain.TargetConstraints{
			SupportsDomainExact: true, SupportsDomainSuffix: true, SupportsIPv4: true, SupportsIPv6: true,
			SupportsPrefixes: true, MaxRules: singbox.MaxEntries, MaxArtifactSize: singbox.MaxArtifactSize,
		},
	}
	clientPlan, err := planner.BuildPlanSet([]planner.ServiceInput{{Definition: definition, Sightings: []domain.Sighting{sighting}}}, clientTarget, now)
	if err != nil {
		t.Fatal(err)
	}
	clientArtifact, err := singbox.Render(clientPlan)
	if err != nil {
		t.Fatal(err)
	}
	if err := singbox.Validate(clientArtifact); err != nil {
		t.Fatalf("client artifact from a discovered draft is invalid: %v", err)
	}
	if !strings.Contains(string(clientArtifact), "example.co.uk") {
		t.Fatalf("client artifact = %s", clientArtifact)
	}
}

func TestWriteLocalDraftNeverReplacesAnExistingDefinition(t *testing.T) {
	t.Run("existing local draft", func(t *testing.T) {
		root := t.TempDir()
		if _, err := WriteLocalDraft(context.Background(), root, draftDefinition()); err != nil {
			t.Fatal(err)
		}
		if _, err := WriteLocalDraft(context.Background(), root, draftDefinition()); !errors.Is(err, ErrDraftExists) {
			t.Fatalf("err = %v, want ErrDraftExists", err)
		}
	})
	t.Run("existing builtin definition", func(t *testing.T) {
		root := t.TempDir()
		builtin := filepath.Join(root, "builtin")
		if err := os.MkdirAll(builtin, 0o700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(builtin, "example.yaml"), []byte(validCatalogYAML), 0o600); err != nil {
			t.Fatal(err)
		}
		if _, err := WriteLocalDraft(context.Background(), root, draftDefinition()); !errors.Is(err, ErrDraftExists) {
			t.Fatalf("err = %v, want ErrDraftExists", err)
		}
	})
	t.Run("no temporary file left behind", func(t *testing.T) {
		root := t.TempDir()
		if _, err := WriteLocalDraft(context.Background(), root, draftDefinition()); err != nil {
			t.Fatal(err)
		}
		entries, err := os.ReadDir(filepath.Join(root, LocalGroup))
		if err != nil {
			t.Fatal(err)
		}
		if len(entries) != 1 || entries[0].Name() != "example.yaml" {
			names := make([]string, 0, len(entries))
			for _, entry := range entries {
				names = append(names, entry.Name())
			}
			t.Fatalf("local directory = %v", names)
		}
	})
}

func TestWriteLocalDraftRefusesAnUnsafeOrUnloadableDefinition(t *testing.T) {
	cases := []struct {
		name       string
		definition func() domain.ServiceDefinition
	}{
		{"invalid identity", func() domain.ServiceDefinition {
			definition := draftDefinition()
			definition.ID = "../escape"
			return definition
		}},
		{"address seed", func() domain.ServiceDefinition {
			definition := draftDefinition()
			definition.Seeds = []domain.Seed{{Kind: domain.RuleIPv4, Value: "192.0.2.10", ComponentID: "core", SourceClass: domain.SourceManual}}
			return definition
		}},
		{"prefix seed", func() domain.ServiceDefinition {
			definition := draftDefinition()
			definition.Seeds = []domain.Seed{{Kind: domain.RulePrefix4, Value: "192.0.2.0/24", ComponentID: "core", SourceClass: domain.SourceManual}}
			return definition
		}},
		{"no seed", func() domain.ServiceDefinition {
			definition := draftDefinition()
			definition.Seeds = nil
			return definition
		}},
		{"no component", func() domain.ServiceDefinition {
			definition := draftDefinition()
			definition.Components = nil
			return definition
		}},
		{"feed source", func() domain.ServiceDefinition {
			definition := draftDefinition()
			definition.Sources = []domain.SourceDefinition{{ID: "feed", Type: domain.SourceHTTP, ComponentID: "core", URL: "https://feeds.example.com/x", Format: domain.FeedFormatText}}
			return definition
		}},
		{"source without names", func() domain.ServiceDefinition {
			definition := draftDefinition()
			definition.Sources = []domain.SourceDefinition{{ID: "dns-core", Type: domain.SourceDNS, ComponentID: "core"}}
			return definition
		}},
		{"unknown component in source", func() domain.ServiceDefinition {
			definition := draftDefinition()
			definition.Sources[0].ComponentID = "other"
			return definition
		}},
	}
	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			root := t.TempDir()
			if _, err := WriteLocalDraft(context.Background(), root, testCase.definition()); err == nil {
				t.Fatal("an unsafe or unloadable draft was written")
			}
			if entries, err := os.ReadDir(filepath.Join(root, LocalGroup)); err == nil && len(entries) != 0 {
				t.Fatalf("a refused draft left %d files behind", len(entries))
			}
		})
	}
}
